<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.props" />

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>

    <!-- Root Namespace -->
    <RootNamespace>PPWCode.Host.Core.WebApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <!-- PPWCode -->
    <PackageReference Include="PPWCode.Vernacular.Exceptions.IV" />
    <PackageReference Include="PPWCode.Vernacular.NHibernate.III" />
    <PackageReference Include="PPWCode.API.Core" />
    <PackageReference Include="PPWCode.Server.Core" />

    <!-- NHibernate -->
    <PackageReference Include="NHibernate" />

  </ItemGroup>

</Project>
